server:
  port: ${PORT:${SERVER_PORT:0}}
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: inventory
    password: inventory_123
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

springdoc:
  api-docs:
    path: /inventory/api-docs
  swagger-ui:
    operationsSorter: method
    path: /inventory/swagger-ui.html