server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "product_db"
      username: "product"
      password: "product"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

springdoc:
  api-docs:
    path: /products/api-docs
  swagger-ui:
    operationsSorter: method
    path: /products/swagger-ui.html